name: Unit and Integration test
on:
  push:
    branches:
      - main
    paths-ignore:
      - "*.md"
  workflow_dispatch:

permissions:
  contents: read

env:
  # Allows ddev get to use a Github token to prevent rate limiting by tests
  DDEV_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  unit-and-integration-tests:
    strategy:
      fail-fast: false
      matrix:
        m2-version: ["2.4.4", "2.4.8"]
        php-version: ["8.1", "8.4"]
        exclude:
          - { php-version: "8.1", m2-version: "2.4.8" }
          - { php-version: "8.4", m2-version: "2.4.4" }
    name: Unit and integration test
    runs-on: ubuntu-latest
    env:
      EXTENSION_PACKAGE_NAME: "ascorak/m2-core"
      EXTENSION_PATH: "m2-core"
    steps:
      - name: Install Magento 2
        uses: julienloizelet/magento2-ddev-installation@v4
        with:
          php_version: ${{ matrix.php-version }}
          magento_version: ${{ matrix.m2-version }}
          composer_auth: ${{ secrets.M2_COMPOSER_AUTH }}
          magento_repository: "https://repo.magento.com/"

      - name: Clone M2 Core module
        uses: actions/checkout@v4
        with:
          path: my-own-modules/${{ env.EXTENSION_PATH }}

      - name: Prepare composer repositories
        run: |
          ddev composer config --unset repositories.0
          ddev composer config repositories.0 '{"type": "path", "url": "my-own-modules/${{ env.EXTENSION_PATH }}", "canonical": true, "options": ["symlink": false]}'
          ddev composer config repositories.1 '{"type": "composer", "url": "https://repo.magento.com/", "exclude": ["${{ env.EXTENSION_PACKAGE_NAME }}"]}'
          cat composer.json

      - name: Add M2 Core Module as composer dependency
        run: |
          ddev composer require ${{ env.EXTENSION_PACKAGE_NAME }}:@dev --no-interaction

      - name: Fix Unit tests for Magento 2.4.6 and 2.4.8
        # @see https://github.com/magento/magento2/issues/36702
        if: contains(fromJSON('["2.4.6", "2.4.8"]'), matrix.m2-version)
        run: sed -i 's/allure\/allure.config.php/dev\/test\/unit\/allure\/allure.config.php/g' dev/tests/unit/phpunit.xml.dist

      - name: Run Unit tests
        run: ddev phpunit vendor/${{ env.EXTENSION_PACKAGE_NAME }}/Test/Unit
